const AVATARS_LIST_API = process.env.REACT_APP_API_BASE_URL + process.env.REACT_APP_AVATARS_LIST_API;
const STREAMERS_LIST_API = process.env.REACT_APP_API_BASE_URL + process.env.REACT_APP_STREAMERS_LIST_API;
const STREAM_DAYS_API = process.env.REACT_APP_API_BASE_URL + process.env.REACT_APP_STREAM_DAYS_API;
const STREAM_CHART_DAILY_API = process.env.REACT_APP_API_BASE_URL + process.env.REACT_APP_STREAM_CHART_DAILY_API;

export {AVATARS_LIST_API, STREAMERS_LIST_API, STREAM_DAYS_API, STREAM_CHART_DAILY_API};